github.com:
    users:
        HaxWire:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: HaxWire
